-- Jira staging views.
-- Keep raw_jira_* as source-faithful ingestion tables and expose typed,
-- BI-friendly columns through stg_* views.

CREATE OR REPLACE VIEW stg_jira_fields AS
SELECT
    field_id,
    field_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.untranslatedName')) AS untranslated_name,
    is_custom,
    is_account_field,
    JSON_EXTRACT(raw_payload, '$.orderable') AS is_orderable,
    JSON_EXTRACT(raw_payload, '$.navigable') AS is_navigable,
    JSON_EXTRACT(raw_payload, '$.searchable') AS is_searchable,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.key')) AS field_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.schema.type')) AS schema_type,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.schema.items')) AS schema_items,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.schema.system')) AS schema_system,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.schema.custom')) AS schema_custom,
    CAST(JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.schema.customId')) AS UNSIGNED) AS schema_custom_id,
    JSON_EXTRACT(raw_payload, '$.schema.configuration') AS schema_configuration,
    JSON_EXTRACT(raw_payload, '$.clauseNames') AS clause_names,
    raw_payload,
    _loaded_at,
    _dlt_load_id,
    _dlt_id
FROM raw_jira_fields;

CREATE OR REPLACE VIEW stg_jira_issues AS
SELECT
    issue_id,
    issue_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.self')) AS issue_self_url,
    account_field_id,
    account_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, CONCAT('$.fields.', account_field_id, '.value'))) AS account_name,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.summary')) AS summary,
    assignee,
    reporter,
    priority,
    resolution,
    labels,
    linked_issues,
    organizations,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.issuetype.id')) AS issue_type_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.issuetype.name')) AS issue_type_name,
    CAST(JSON_EXTRACT(raw_payload, '$.fields.issuetype.subtask') AS UNSIGNED) AS is_subtask,
    CAST(JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.issuetype.hierarchyLevel')) AS SIGNED) AS issue_type_hierarchy_level,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.id')) AS project_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.key')) AS project_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.name')) AS project_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.projectTypeKey')) AS project_type_key,
    CAST(JSON_EXTRACT(raw_payload, '$.fields.project.simplified') AS UNSIGNED) AS is_project_simplified,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.projectCategory.id')) AS project_category_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.project.projectCategory.name')) AS project_category_name,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.id')) AS status_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.name')) AS status_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.statusCategory.id')) AS status_category_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.statusCategory.key')) AS status_category_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.statusCategory.colorName')) AS status_category_color,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.status.statusCategory.name')) AS status_category_name,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.id')) AS parent_issue_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.key')) AS parent_issue_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.summary')) AS parent_summary,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.issuetype.id')) AS parent_issue_type_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.issuetype.name')) AS parent_issue_type_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.status.id')) AS parent_status_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.status.name')) AS parent_status_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.status.statusCategory.key')) AS parent_status_category_key,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.status.statusCategory.colorName')) AS parent_status_category_color,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.status.statusCategory.name')) AS parent_status_category_name,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.priority.id')) AS parent_priority_id,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.parent.fields.priority.name')) AS parent_priority_name,

    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.created')) AS created_raw,
    JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.updated')) AS updated_raw,
    resolved_at,
    due_date,
    attivita_su_db,
    categoria,
    categoria_sql,
    comando_sql,
    data_tk_axel,
    data_stima_approvata,
    impatto_incident,
    kpi_breached,
    oda_ordine_di_acquisto,
    presa_in_carico,
    processi,
    prodotti,
    satisfaction,
    satisfaction_date,
    sla_amco,
    sla_ing,
    sla_sb,
    stima_approvata,
    stima_intervento_ore,
    priorita_cliente,
    sla_ticket,
    tempo_di_presa_in_carico,
    service_desk_time,
    tipo_attivita,
    bpo_amco,
    bpo_ampre,
    bpo_jj_tatooine,
    sow_statement_of_work,
    data_presa_in_carico,
    sla_kpi_presa_in_carico,
    sla_elapsed,
    STR_TO_DATE(SUBSTRING(JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.created')), 1, 23), '%Y-%m-%dT%H:%i:%s.%f') AS created_at,
    STR_TO_DATE(SUBSTRING(JSON_UNQUOTE(JSON_EXTRACT(raw_payload, '$.fields.updated')), 1, 23), '%Y-%m-%dT%H:%i:%s.%f') AS updated_at,

    raw_payload,
    _loaded_at,
    _dlt_load_id,
    _dlt_id
FROM raw_jira_issues;
